config/routes.rb
Rails.application.routes.draw do
  resources :sport_centers
  resources :events
  resources :coaches
  resources :users
  resources :register
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/sport_center.rb
class SportCenter < ApplicationRecord
  has_many :events
end

app/controllers/sport_centers_controller.rb
class SportCentersController < ApplicationController
  before_action :set_sport_center, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /sport_centers
  # GET /sport_centers.json
  def index
    @sport_centers = SportCenter.all
  end

  # GET /sport_centers/1
  # GET /sport_centers/1.json
  def show
  end

  # GET /sport_centers/new
  def new
  end

  # GET /sport_centers/1/edit
  def edit
  end

  # POST /sport_centers
  # POST /sport_centers.json
  def create
    @sport_center = SportCenter.new(sport_center_params)

    respond_to do |format|
      if @sport_center.save
        format.html { redirect_to @sport_center, notice: 'Sport center was successfully created.' }
        format.json { render :show, status: :created, location: @sport_center }
      else
        format.html { render :new }
        format.json { render json: @sport_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sport_centers/1
  # PATCH/PUT /sport_centers/1.json
  def update
    respond_to do |format|
      if @sport_center.update(sport_center_params)
        format.html { redirect_to @sport_center, notice: 'Sport center was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport_center }
      else
        format.html { render :edit }
        format.json { render json: @sport_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sport_centers/1
  # DELETE /sport_centers/1.json
  def destroy
    @sport_center.destroy
    respond_to do |format|
      format.html { redirect_to sport_centers_url, notice: 'Sport center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport_center
      @sport_center = SportCenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_center_params
      params.require(:sport_center).permit(:name, :email, :encrypted_password, :location, :description, :photo, :phone_number)
    end
end

app/helpers/sport_centers_helper.rb
module SportCentersHelper
end

app/views/sport_centers/_form.html.erb
<div class="forms">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <% @sport_center = SportCenter.new %>
        <%= form_for @sport_center, url: {controller: 'sport_centers', action: 'create'} do |form| %>
          <br />
          <p>
            <label for="centur_name">Спортен център:</label>
            <%= form.text_field :name, id: :centur_name, class: 'form-control', placeholder: 'Име и фамилия' %>
          </p>
          <p>
            <label for="centur_email">E-mail:</label>
            <%= form.text_field :email, id: :centur_email, class: 'form-control', placeholder: 'E-mail' %>
          </p> 
          <p>
            <label for="centur_password">Парола:</label>
            <%= form.text_field :encrypted_password, id: :centur_password, class: 'form-control', placeholder: 'Парола' %>
          </p>
          <p>
            <label for="centur_password_repeat">Повтаряне на паролата:</label>
            <%= form.text_field :encrypted_password, id: :centur_password_repeat, class: 'form-control', placeholder: 'Повтаряне на паролата' %>
          </p>
          <p>
            <label for="centur_phone">Телефон:</label>
            <%= form.text_field :phone_number, id: :centur_phone, class: 'form-control', placeholder: 'Телефон' %>
          </p>
          <p>
            <label for="centur_location">Местоположение:</label>
            <%= form.text_field :location, id: :centur_location, class: 'form-control', placeholder: 'Местоположение' %>
          </p>
          <p>
            <label for="centur_description">Описание:</label>
            <%= form.text_area :description, id: :sport_center_description, name: :centur_description, class: 'form-control', placeholder: "Описание" %>
          </p>

          <br/>
          <%= form.submit name: :submit_form, value: 'Изпрати', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sport_centers/edit.html.erb
<h1>Editing Sport Center</h1>

<%= render 'form', sport_center: @sport_center %>

<%= link_to 'Show', @sport_center %> |
<%= link_to 'Back', sport_centers_path %>

app/views/sport_centers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sport Centers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Location</th>
      <th>Description</th>
      <th>Photo</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sport_centers.each do |sport_center| %>
      <tr>
        <td><%= sport_center.name %></td>
        <td><%= sport_center.email %></td>
        <td><%= sport_center.encrypted_password %></td>
        <td><%= sport_center.location %></td>
        <td><%= sport_center.description %></td>
        <td><%= sport_center.photo %></td>
        <td><%= sport_center.phone_number %></td>
        <td><%= link_to 'Show', sport_center %></td>
        <td><%= link_to 'Edit', edit_sport_center_path(sport_center) %></td>
        <td><%= link_to 'Destroy', sport_center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport Center', new_sport_center_path %>

app/views/sport_centers/new.html.erb
<main class="registration">
  <div class="header">
      <div class="container ">
          <div class="row">
              <div class="col-xs-12 text-center">
                  <h1>Спорт за Всички</h1>
              </div>
          </div>
          
      </div>
  </div>
  <div class="container ">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h2>Добавяне на спортен център</h2>
      </div>
    </div>
  </div>
<%= render 'form', sport_center: @sport_center %>
</main>

app/views/sport_centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport_center.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sport_center.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @sport_center.encrypted_password %>
</p>

<p>
  <strong>Location:</strong>
  <%= @sport_center.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sport_center.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @sport_center.photo %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @sport_center.phone_number %>
</p>

<%= link_to 'Edit', edit_sport_center_path(@sport_center) %> |
<%= link_to 'Back', sport_centers_path %>