config/routes.rb
Rails.application.routes.draw do
  resources :sport_centers
  resources :events
  resources :coaches
  resources :users
  resources :register
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :coach, required: false
  belongs_to :sport_centre, required: false
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    puts "++++++++++++++++++++"
    p event_params
    puts "++++++++++++++++++++"
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:category, :location, :date, :description, :coach_name, :photo)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% 
  sport_events   = "['sport_events']"
  rehab_sessions = "['rehab_sessions']"
  categories = {
    'Плуване' => sport_events,
    'Ветроходство' => sport_events,
    'Унидсърф' => sport_events,
    'Водна топка' => sport_events,
    'Волейбол' => sport_events,
    'Футбол' => sport_events,
    'Художествена гимнастика' => sport_events,
    'Спортни танци' => sport_events,
    'Вани' => rehab_sessions,
    'Басейн подводна гиманстика' => rehab_sessions,
    'Луголечение' => rehab_sessions,
    'Парафинолечение' => rehab_sessions,
    'Физиотерапия' => rehab_sessions,
    'Масаж' => rehab_sessions,
    'Кинезитерапия' => rehab_sessions,
  }
%>
<%= content_tag(:li, nil, class: "col-xs-12 col-sm-4 event", :data => {:'groups' => "#{categories[event.category]}"}) do  %>
  <div class="event-box">
    <div class="col-xs-12 ">
      <h2><%= event.category %></h2>
    </div>
    <div class="col-xs-12">
      <p>Местоположение: <span><%= event.location %></span></p>
      <p>Дата: <span><%= event.date %></span></p>
    </div>
    <div class="col-xs-12">
      <a href="" >Запиши се</a>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<div class="forms">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for @event, model: event, url: {action: 'create'} do |form| %>
          <div class="alert hidden" id="output_centur"></div>
          <p>
            <%= form.label :category, "Категория:" %>
            <%= form.select :category, nil, {}, { class: 'form-control'} do %>
              <option>--</option>
              <optgroup label="Спортове">
                <option value='Плуване'>Плуване</option>
                <option value='Ветроходство'>Ветроходство</option>
                <option value='Унидсърф'>Унидсърф</option>
                <option value='Водна топка'>Водна топка</option>
                <option value='Волейбол'>Волейбол</option>
                <option value='Футбол'>Футбол</option>
                <option value='Художествена гимнастика'>Художествена гимнастика</option>
                <option value='Спортни танци'>Спортни танци</option>
              </optgroup>
              <optgroup label="Рехабилитация">
                <option value='Вани'>Вани</option>
                <option value='Басейн подводна гиманстика'>Басейн подводна гиманстика</option>
                <option value='Луголечение'>Луголечение</option>
                <option value='Парафинолечение'>Парафинолечение</option>
                <option value='Физиотерапия'>Физиотерапия</option>
                <option value='Масаж'>Масаж</option>
                <option value='Кинезитерапия'>Кинезитерапия</option>
              </optgroup>
              <% end %>
          </p>
          <p>
            <label for="event_date">Дата:</label>
            <%= form.text_field :date, id: :event_date, class: "form-control", placeholder: "Дата", type: 'date' %>
          </p>
           <p>
            <label for="event_location">Местоположение:</label>
            <%= form.text_field :location, id: :event_location, class: "form-control", placeholder: "Местоположение" %>
          </p>
          <p>
            <label for="event_couch">Име на треньор:</label>
            <%= form.text_field :coach_name, id: :event_coach_name, class: "form-control", placeholder: "Име на треньор" %>
          </p>
           <p>
            <label for="event_description">Описание:</label>
            <%= form.text_area :description, class: "form-control", placeholder: "Описание", rows: 5 %>
          </p>
          <%= form.submit name: :submit_form, value: 'Изпрати', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<main>
  <div class="home">
    <div class="header-image text-center">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1>Спорт за всички</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <div class="filter-options">
            <button class="home-btns active" data-group="all">Всички</button>
            <button class="home-btns " data-group="sport_events">Спортни тренировки</button>
            <button class="home-btns" data-group="rehab_sessions">Рехабилитационни процедури</button>
          </div>
        </div>
      </div>
    </div>

    <p id="notice"><%= notice %></p>
    <div class="container-fluid" id="shuffle-projects">
      <div class="row">
        <ul class="list-unstyled" id="grid">
          <%= render @events %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/events/new.html.erb
<main class="registration">
  <div class="header">
      <div class="container ">
          <div class="row">
              <div class="col-xs-12 text-center">
                  <h1>Спорт за Всички</h1>
              </div>
          </div>
          
      </div>
  </div>
  <div class="container ">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h2>Добавяне на събитие</h2>
      </div>
    </div>
  </div>
  <%= render 'form', event: @event %>
</main>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @event.category %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Coach name:</strong>
  <%= @event.coach_name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @event.photo %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>