config/routes.rb
Rails.application.routes.draw do
  resources :sport_centers
  resources :events
  resources :coaches
  resources :users
  resources :register
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/coach.rb
class Coach < ApplicationRecord
  has_many :events
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:name, :email, :encrypted_password, :phone_number, :date_of_birth, :photo, :specialization)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<div class="forms">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <% @coach = Coach.new %>
        <%= form_for @coach, url: {controller: 'coaches', action: 'create'}, :html => {:class => "form-horizontal"} do |form| %>
          <br />
          <p>
            <label for="coach_name">Име и фамилия:</label>
            <%= form.text_field :name, id: :coach_name, class: 'form-control', placeholder: 'Име и фамилия' %>
          </p>
          <p>
            <label for="coach_email">E-mail:</label>
            <%= form.text_field :email, id: :coach_email, class: 'form-control', placeholder: 'E-mail' %>
          </p> 
          <p>
            <label for="coach_password">Парола:</label>
            <%= form.text_field :encrypted_password, id: :coach_password, class: 'form-control', placeholder: 'Парола' %>
          </p>
          <p>
            <label for="coach_password_repeat">Повтаряне на паролата:</label>
            <%= form.text_field :encrypted_password, id: :coach_password_repeat, class: 'form-control', placeholder: 'Повтаряне на паролата' %>
          </p>
          <p>
            <label for="coach_phone">Телефон:</label>
            <%= form.text_field :phone_number, id: :coach_phone, class: 'form-control', placeholder: 'Телефон' %>
          </p>
          <p>
            <label for="coach_birthdate">Дата на раждане:</label>
            <%= form.text_field :date_of_birth, id: :coach_birthdate, class: 'form-control', placeholder: 'Дата на раждане', type: 'date' %>
          </p>

          <p>
            <h2>Специализация</h2>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <h3>Спортове</h3>
                     <ul>
                        <li>
                            <label for="sport_1">Плуване</label>
                            <input type="checkbox" name="sport_1" value="Плуване" >
                        </li>
                        <li>
                            <label for="sport_2">Ветроходство</label>
                            <input type="checkbox" name="sport_2" value="Ветроходство" >
                        </li>
                         <li>
                            <label for="sport_3">Унидсърф</label>
                            <input type="checkbox" name="sport_3" value="Унидсърф" >
                        </li>
                         <li>
                            <label for="sport_4">Водна топка</label>
                            <input type="checkbox" name="sport_4" value="Водна топка" >
                        </li>
                         <li>
                            <label for="sport_5">Волейбол</label>
                            <input type="checkbox" name="sport_5" value="Волейбол" >
                        </li>
                        <li>
                            <label for="sport_6">Футбол</label>
                            <input type="checkbox" name="sport_6" value="Футбол" >
                        </li>
                         <li>
                            <label for="sport_7">Художествена гимнастика</label>
                            <input type="checkbox" name="sport_7" value="Художествена гимнастика" >
                        </li>
                         <li>
                            <label for="sport_8">Спортни танци</label>
                            <input type="checkbox" name="sport_8" value="Спортни танци" >
                        </li>
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <h3>Рехабилитация</h3>
                     <ul>
                        <li>
                            <label for="rehab_1">Вани</label>
                            <input type="checkbox" name="sport_1" value="Вани" >
                        </li>
                        <li>
                            <label for="rehab_2">Басейн подводна гиманстика</label>
                            <input type="checkbox" name="rehab_2" value="Басейн подводна гиманстика" >
                        </li>
                        <li>
                            <label for="rehab_3">Луголечение</label>
                            <input type="checkbox" name="rehab_3" value="Луголечение" >
                        </li>
                        <li>
                            <label for="rehab_4">Парафинолечение</label>
                            <input type="checkbox" name="rehab_4" value="Парафинолечение" >
                        </li>
                        <li>
                            <label for="rehab_5">Физиотерапия</label>
                            <input type="checkbox" name="rehab_5" value="Физиотерапия" >
                        </li>
                        <li>
                            <label for="rehab_6">Масаж</label>
                            <input type="checkbox" name="rehab_6" value="Масаж" >
                        </li>
                        <li>
                            <label for="rehab_7">Кинезитерапия</label>
                            <input type="checkbox" name="rehab_7" value="Кинезитерапия" >
                        </li>                                                        
                    </ul>
                </div>
            </div>
          </p>  
          <%= form.submit name: :submit_form, value: 'Изпрати', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Phone number</th>
      <th>Date of birth</th>
      <th>Photo</th>
      <th>Specialization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= coach.email %></td>
        <td><%= coach.encrypted_password %></td>
        <td><%= coach.phone_number %></td>
        <td><%= coach.date_of_birth %></td>
        <td><%= coach.photo %></td>
        <td><%= coach.specialization %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :destroy, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<main class="registration">
  <div class="header">
      <div class="container ">
          <div class="row">
              <div class="col-xs-12 text-center">
                  <h1>Спорт за Всички</h1>
              </div>
          </div>
          
      </div>
  </div>
  <div class="container ">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h2>Добавяне на треньор</h2>
      </div>
    </div>
  </div>
<%= render 'form', coach: @coach %>
</main>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coach.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @coach.encrypted_password %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @coach.phone_number %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @coach.date_of_birth %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @coach.photo %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @coach.specialization %>
</p>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>